version: '2.4'

services:

  omnom-db:
    image: postgres:latest
    restart: always
    ports:
      - 127.0.0.1:${OMNOM_DB_PORT}:${OMNOM_DB_PORT}
    volumes:
      - ./omnom-db:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}" ]
        interval: 1s
        timeout: 1s
        retries: 60

  omnom-backend:
    image: omnom-backend:latest
    env_file: .env
    ports:
      - ${OMNOM_BACKEND_PORT}:${OMNOM_BACKEND_PORT}
    depends_on:
      omnom-db:
        condition: service_healthy
