version: '2.4' # version 3 doesn't support depends_on.option

services:
  omnom-auth:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    env_file: .env
    ports:
      - "${OMNOM_AUTH_PORT}:${OMNOM_AUTH_PORT}"
    volumes:
      - ./omnom-auth/omnom-auth-testdata/:/opt/keycloak/data/
    command: [ "start-dev --http-port ${OMNOM_AUTH_PORT}" ]

  omnom-db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "${OMNOM_DB_PORT}:${OMNOM_DB_PORT}"
    volumes:
      - ./omnom-db/config:/db-config
      - ./omnom-db/init:/docker-entrypoint-initdb.d
      - ./omnom-db/omnom-db-testdata:/var/lib/postgresql/data
    command: "-p ${OMNOM_DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 1s
      timeout: 1s
      retries: 60

  omnom-backend:
    build:
      context: ./omnom-backend
#    image: omnom-backend:latest
    env_file: .env
    ports:
      - "${OMNOM_BACKEND_PORT}:${OMNOM_BACKEND_PORT}"
    depends_on:
      omnom-db:
        condition: service_healthy

#  omnom-frontend:
#    image: omnom-frontend:latest
#    ports:
#      - "${OMNOM_FRONTEND_PORT}:80"
