quarkus:
  http:
    port: 8080
    cors: true
  hibernate-orm:
    database:
      generation: none

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: OmNom Backend API
          version: 0.1
