name: Build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./omnom-backend
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Java
      run: mvn package
    - name: Build Docker
      run: docker build -f src/main/docker/Dockerfile.jvm -t omnom-backend .
    - name: Push Docker
      run: |
        docker login --username ${{secrets.DOCKER_REGISTRY_USERNAME}} --password ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        docker tag omnom-backend ${{secrets.DOCKER_REGISTRY_URL}}/omnom-backend
        docker push ${{secrets.DOCKER_REGISTRY_URL}}/omnom-backend
        
        
